/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedMerchantsIndexRouteImport } from './routes/_authenticated/merchants/index'
import { Route as AuthenticatedMerchantsIdRouteImport } from './routes/_authenticated/merchants/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchantsIndexRoute =
  AuthenticatedMerchantsIndexRouteImport.update({
    id: '/merchants/',
    path: '/merchants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantsIdRoute =
  AuthenticatedMerchantsIdRouteImport.update({
    id: '/merchants/$id',
    path: '/merchants/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/merchants/$id': typeof AuthenticatedMerchantsIdRoute
  '/merchants/': typeof AuthenticatedMerchantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/merchants/$id': typeof AuthenticatedMerchantsIdRoute
  '/merchants': typeof AuthenticatedMerchantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/merchants/$id': typeof AuthenticatedMerchantsIdRoute
  '/_authenticated/merchants/': typeof AuthenticatedMerchantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/prices'
    | '/merchants/$id'
    | '/merchants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/prices'
    | '/merchants/$id'
    | '/merchants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/_authenticated/prices'
    | '/_authenticated/merchants/$id'
    | '/_authenticated/merchants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchants/': {
      id: '/_authenticated/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof AuthenticatedMerchantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchants/$id': {
      id: '/_authenticated/merchants/$id'
      path: '/merchants/$id'
      fullPath: '/merchants/$id'
      preLoaderRoute: typeof AuthenticatedMerchantsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedMerchantsIdRoute: typeof AuthenticatedMerchantsIdRoute
  AuthenticatedMerchantsIndexRoute: typeof AuthenticatedMerchantsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedMerchantsIdRoute: AuthenticatedMerchantsIdRoute,
  AuthenticatedMerchantsIndexRoute: AuthenticatedMerchantsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
